apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: argocd-configmap
    files:
      - json/argocd.json
    # Specify labels for the generated ConfigMap
    labels:
      grafana_dashboard: "1"

