apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: argocd-configmap
    files:
      - json/argocd.json
  - name: ingress-controller-configmap
    files:
      - json/ingress-controller.json    
     
generatorOptions:
  
  labels:
    grafana_dashboard: "1"    
    


